title : Tech Gypsies

safe: true
lsi: false
pygments: true
auto: true

source: techgypsies
destination: techgypsies

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 1000
paginate_path: "/blog/page:num"

production_url : http://techgypsi.es/

BASE_PATH : http://techgypsi.es/

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
